language: node_js
node_js:
  - "lts/*"
before_deploy:
  - "npm run build"
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - "dist/color-generator.js"
    - "dist/color-generator.min.js"
  skip_cleanup: true
  on:
    tags: true
